### ISSUE TITLE
Basic controller

### ISSUE THREAD

**Issue by hamzehmohammadnia** [intrig-unicamp/mininet-wifi#102]
Hi @ramonfontes ,

I had some thoughts through working with Mininet-wifi, with holding your description about:
a) If need to add a remote controller it needs to handle mobility or do it manually
b). current mininet-wifi is working with reference controller (default controller)

Now I have two questions:

is the reference controller defined in node.py at line number 2278: class Controller(Node)?

As you said earlier, the reference controller that is used for mininet in default is from mininet, right? then if I change the option parameter of --controller=remote controller and run

https://github.com/itaimirin/SDN-Controller---Mininet-POX-/blob/master/IM_l2_learning.py

it will work properly?

and last but not least, since you mentioned this is a wireless station (access point) that acts like a switch, and since when I traced controller on wireshark I have seen Port_in and Port_out flows, how controller setups rules on the access points (ovs switch) ? cuz there is no port to setup rules on it...
Thank you in advance,
Best,

**Comment by ramonfontes** [comment]
*Hello,*

2017-08-25 11:21 GMT-03:00 hamzehmohammadnia <notifications@github.com>:

> Hi @ramonfontes <https://github.com/ramonfontes> ,
>
> I had some thoughts through working with Mininet-wifi, with holding your
> description about:
> a) If need to add a remote controller it needs to handle mobility or do it
> manually
> b). current mininet-wifi is working with reference controller (default
> controller)
>
> Now I have two questions:
>
> is the reference controller defined in node.py at line number 2278: class
> Controller(Node)?
>
*It's defined from the OpenFlow reference implementation
(ovs-testcontroller). *

> As you said earlier, the reference controller that is used for mininet in
> default is from mininet, right? then if I change the option parameter of
> --controller=remote controller and run
>
> https://github.com/itaimirin/SDN-Controller---Mininet-POX-/
> blob/master/IM_l2_learning.py
>
> it will work properly?
>
*It won't work only when flows 'come from and go to' the same interface.
For example:*


*sta1 --- (wlan1) ap1 (wlan1) --- sta2*


*It will work for the rest. For example:*

*sta1 -- ap1 --- ap2 --- sta2 *
*sta1 -- ap1 -- s1 --- h1*
*sta1 -- ap1 -- s1 --- ap2 --- sta2*

*and so on...*

and last but not least, since you mentioned this is a wireless station
> (access point) that acts like a switch, and since when I traced controller
> on wireshark I have seen Port_in and Port_out flows, how controller setups
> rules on the access points (ovs switch) ? cuz there is no port to setup
> rules on it...
>
*There is the wlan interface (port number 1 by default).*

**Comment by hamzehmohammadnia** [comment]
Hi,
Hi,
There is an issue when using l2_learning pox controller. lots of warning messages pops up on the controller screen when use mininet --wifi. While using the same controller of pox with mininet (using mininet vm iso of virtual machine) shows no error and seems all fine. 
The issues point at DNS.py and IPv6.py files of packets in pox controller. Are you sure it properly works with simple controller?

while runnig ./pox.py forwarding.l2_learning and  running: mn --wifi .... --controller remote
INFO:packet:(ipv6) warning IP packet data incomplete (114 of 229)
INFO:packet:(dns) parsing answers: next_rr: data truncated

Best,

**Comment by ramonfontes** [comment]
The warning is due the number of devices connected to the same port (AP's
port). But it works fine. Please see:
https://m.youtube.com/watch?v=2FjAS8g5Bsk

Sent from my android

On 31 Aug 2017 09:34, "hamzehmohammadnia" <notifications@github.com> wrote:

Hi,
Hi,
There is an issue when using l2_learning pox controller. lots of warning
messages pops up on the controller screen when use mininet --wifi. While
using the same controller of pox with mininet (using mininet vm iso of
virtual machine) shows no error and seems all fine.
The issues point at DNS.py and IPv6.py files of packets in pox controller.
Are you sure it properly works with simple controller?

while runnig ./pox.py forwarding.l2_learning and running: mn --wifi ....
--controller remote
INFO:packet:(ipv6) warning IP packet data incomplete (114 of 229)
INFO:packet:(dns) parsing answers: next_rr: data truncated

Best,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/102#issuecomment-326281613>,
or mute the thread

**Comment by hamzehmohammadnia** [comment]
Thanks, 
I have checked with this topology:
sta1 -- ap1 --- ap2 --- sta2  
but will check with your example code (raduis). 
Best,

**Comment by hamzehmohammadnia** [comment]
Hi,
After testing your Radius topology with "sudo mn --wifi --topo radius.py --controller remote " command, it started to work  and also no error showed up on the controller screen. (i hope the way of used topology would be fine)
But within topology, I found a parameter that called "radius_passwd" in  [1], at line 6 and 7. I was wondering since these two mobile stations are connected to the same access point, then why they use different wifi password? did I understood radius_passwd parameter correctly?

Best,





[1] https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/radius/radiusCode.py

**Comment by ramonfontes** [comment]
There is nothing special about using different usernames/passwords. You can
use the same username/passwd if you want. You just have to take care about
the radius configuration file and where you are running it.

By default, when radius server ip isn't configured, it assumes 127.0.0.1
(e.g. radius_server='127.0.0.1'). So, if there is only one AP and you have
only one radius server, all stations should be associated to the same AP
(if username/passwd are correct, of course).

BTW, you can use iw/iwconfig if you want to verify associations.



2017-09-02 14:03 GMT-03:00 hamzehmohammadnia <notifications@github.com>:

**Comment by hamzehmohammadnia** [comment]
Im facing with a weird error of not being able to import mininet modules. 
~/mininet-wifi/examples$ sudo python radius/radiusCode.py 
Traceback (most recent call last):
  File "radius/radiusCode.py", line 5, in <module>
    from mininet.net import Mininet
ImportError: No module named mininet.net

or when 

:~/mininet-wifi/examples/radius$ sudo ./radiusCode.py 
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
*** Associating Stations
Associating sta1-wlan0 to ap1
Associating sta2-wlan0 to ap1
*** Starting network
Traceback (most recent call last):
  File "./radiusCode.py", line 47, in <module>
    topology()
  File "./radiusCode.py", line 32, in topology
    net.build()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/net.py", line 923, in build
    mininetWiFi.configureWmediumd(self.stations, self.accessPoints)
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/wifiNet.py", line 656, in configureWmediumd
    WmediumdStarter.start()
  File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/wmediumdConnector.py", line 434, in start
    stderr=subprocess.STDOUT, preexec_fn=os.setpgrp)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Im runnig this to test your raduis topology and pox controller. 
I have tried it with mininet vm image and tested a customized topology but didnt face the same error as I see on mininet-wifi vm. According to you instruction I didnt see any specific python package installation, except apt-get updating after a fresh ubuntu installation


Best,

**Comment by ramonfontes** [comment]
Are you sure you are using our VM? I don't think so. You would never get
such error. Specially the first one.

Sent from my android

On 2 Sep 2017 17:44, "hamzehmohammadnia" <notifications@github.com> wrote:

Im facing with a weird error of not being able to import mininet modules.
~/mininet-wifi/examples$ sudo python radius/radiusCode.py
Traceback (most recent call last):
File "radius/radiusCode.py", line 5, in
from mininet.net import Mininet
ImportError: No module named mininet.net

or when

:~/mininet-wifi/examples/radius$ sudo ./radiusCode.py
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
*** Associating Stations
Associating sta1-wlan0 to ap1
Associating sta2-wlan0 to ap1
*** Starting network
Traceback (most recent call last):
File "./radiusCode.py", line 47, in
topology()
File "./radiusCode.py", line 32, in topology
net.build()
File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/net.py",
line 923, in build
mininetWiFi.configureWmediumd(self.stations, self.accessPoints)
File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-py2.7.egg/mininet/wifiNet.py",
line 656, in configureWmediumd
WmediumdStarter.start()
File "/usr/local/lib/python2.7/dist-packages/mininet-2.1.post2-
py2.7.egg/mininet/wmediumdConnector.py", line 434, in start
stderr=subprocess.STDOUT, preexec_fn=os.setpgrp)
File "/usr/lib/python2.7/subprocess.py", line 711, in *init*
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory

Im runnig this to test your raduis topology and pox controller.
I have tried it with mininet vm image and tested a customized topology but
didnt face the same error as I see on mininet-wifi vm. According to you
instruction I didnt see any specific python package installation, except
apt-get updating after a fresh ubuntu installation

Best,

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/102#issuecomment-326768394>,
or mute the thread

**Comment by hamzehmohammadnia** [comment]
I have followed this [1] which was pretty easy and straight forward to install mininet-wifi.


[1] http://www.brianlinkletter.com/mininet-wifi-software-defined-network-emulator-supports-wifi-networks/

**Comment by ramonfontes** [comment]
The best reference is (always) the source code page of the tool you want to
work.

Please refer to the Mininet-WiFi's source code repository.
