### ISSUE TITLE
Mobile ad hoc network

### ISSUE THREAD

**Issue by iamxg** [intrig-unicamp/mininet-wifi#132]
Hi Ramon,
How are you?
I am emulating MANET in this emulator. I hope that two nodes can exchange data when they encounter. But I don't know how to detect whether one node is in communication range of another node. Could you give me some suggestion? Thanks a lot!

Best Regards,
Xian

**Comment by ramonfontes** [comment]
Dear Xian,

You can use iw/iwconfig for that.

Sent from my android

On 3 Nov 2017 01:40, "Xian Guo" <notifications@github.com> wrote:

Hi Ramon,
How are you?
I am emulating MANET in this emulator. I hope that two nodes can exchange
data when they encounter. But I don't know how to detect whether one node
is in communication range of another node. Could you give me some
suggestion? Thanks a lot!

Best Regards,
Xian

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/132>, or mute the
thread

**Comment by iamxg** [comment]
Hi, 
Good morning！
Thank you very much for your reply timely！I will try it.
have a good day！
Xian
