### ISSUE TITLE
Issue in running ieee80211p.py file 

### ISSUE THREAD

**Issue by varunpsarvade** [intrig-unicamp/mininet-wifi#198]
When I run ieee80211p.py from examples folder i get the following message. Can any one guide me how to over come this error and i have not made any changes in the file. I am trying to run this using VM downloaded from the link in Mininet wifi manual. I have even tried running sudo mn -c, still i get the same error.
*** Creating nodes
*** Configuring Propagation Model
*** Configuring wifi nodes
insmod: ERROR: could not load module ./mac80211_hwsim.ko: No such file or directory
Warning! Error when loading mac80211_hwsim. Please run sudo 'mn -c' before running your code.
Further information available at /tmp/mn-wifi-mac80211_hwsim.log.

**Comment by varunpsarvade** [comment]
Hi Ramon Fontes, 
Thank you for such early reply.I have read the user manual and followed the steps given in 802.11p section and installed wireless-regdb and CRDA successfully. even after that i am getting the above mentioned error.

Regards, 
Varun

**Comment by ramonfontes** [comment]
Dear,

The msg says "mac80211_hwsim.ko: No such file or directory". Hence, It means that you haven't compiled mac80211_hwsim with the modifications.

**Comment by varunpsarvade** [comment]
Ok I will do the modifications and check. Thank you very much.
Regards,
Varun

**Comment by ramonfontes** [comment]
I just updated the manual and instructions on how to compile mac80211_hwsim was added.

**Comment by daviddvs** [comment]
Hi, 
I cannot modify the mac80211_hwsim.c file because it does not exist. I can only see the mac80211_hwsim.ko file. I use the official VM of Mininet-WiFi with Ubuntu 16.
David

**Comment by ramonfontes** [comment]
Please consider to use a mac80211_hwsim version from https://github.com/torvalds/linux/blob/master/drivers/net/wireless/mac80211_hwsim.c which matches with your kernel version.

**Comment by ramonfontes** [comment]
Dear, it doesn't matter if you're using Ubuntu 14.04, 16.04, 18.04, etc. Everything you need is to take into account your **kernel version** and compile the module with the `Makefile`.

**Comment by daviddvs** [comment]
Finally it is working. 
I downloaded the module version corresponding to my kernel (two files: `mac80211_hwsim.c` and `mac8011_hwsim.h`) and compiled them following the steps suggested in the User Manual. After this, I replaced the original `mac80211_hwsim.ko` file by the modified/compiled one and I commented the line that loads the module (net.setModule) in the `ieee80211p.py` example. I did this in order to call modprobe instead of  insmod and avoid manually loading module dependencies. Maybe any reference to this could be included in the User Manual.

Thank you very much !!!!!!!!
