### ISSUE TITLE
Problem in vanet-sumo.py

### ISSUE THREAD

**Issue by pegahnikbakht** [intrig-unicamp/mininet-wifi#213]
When I run vanet-sumo.py, the added cars doesn't show in sumo-gui or actually I can not see any moving. How do you define route in sumo-vanet.py?

**Comment by ramonfontes** [comment]
You need to add cars as well routes in xml files at https://github.com/intrig-unicamp/mininet-wifi/tree/master/mn_wifi/sumo/data.

**Comment by pegahnikbakht** [comment]
Thanks, do you know how is it possible to take car parameters like speed, waitingtime, and so on in sumo-vanet.py?

**Comment by ramonfontes** [comment]
You don't need to configure those parameters in vanet-sumo.py. They need to be configured in SUMO.

**Comment by pegahnikbakht** [comment]
I know that there is no need to configure them for running vanet-sumo.py , but I'm working on another project where I need to send these parameters to my remote controller. Do you know how I can access these parameters and send them to the remote controller?

**Comment by ramonfontes** [comment]
In this case you may need to take a look at the sumo's api and take those paremeters as we do with the position. See (L100)[https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/sumo/runner.py#L100].

**Comment by lamiael16** [comment]
> When I run vanet-sumo.py, the added cars doesn't show in sumo-gui or actually I can not see any moving. How do you define route in sumo-vanet.py?
Hi,
Please, I used this script and I had problem with number of cars, did you try it with more than 30 cars, did you have problem like sumo stop and no cars move? please can you help me I must finish my work this week and no idea about how I will manage this problem.
I try to use different versions of SUMO but it didn't work, I also try different openstreetmap configuration but no things change.
Also, I want to know, did you send cars information to controller ?
Thank you.

**Comment by ramonfontes** [comment]
net, poly and route files are defined in https://github.com/intrig-unicamp/mininet-wifi/tree/master/mn_wifi/sumo/data. You can replace them with your files and recompile the code in order to apply the changes.

**Comment by lamiael16** [comment]
Hi Ramon,
I did all what you say but it didn't work when the number of cars is more
than 20 cars, I generate a net.xml, rou.xml files for 10 cars and 20 cars
all work fine but when I put 40 cars and more, SUMO stop after 20 sec and
all ifconfig of cars return no access point attached, also all ping command
give me unreachable response.
please can help me because I must present my work to evaluate different
controller in different vehicles density using mining-wifi next week and I
stuck on.
thank you.

**Comment by ramonfontes** [comment]
It seems to be a problem with your SUMO files. So, I suggest you to contact its mailing list.

**Comment by lamiael16** [comment]
Thank you for your response,
I tried different version of sumo from 0.25.0 to 1.2.0 all have problems,
sometimes it is storage problem reading of 4 bytes caused by Traci version
with mininet-wifi version and when I upgrade to new version 1.1.0 (what I
used now) I had the problem of time execution is less then what I want ( I
juste need 150 s just to do ping and Iperf commande and have the result).
I will contact them, but did you try your valet-sumo.py with more than 10
vehicles and work?
please can you try juste 70 vehicles?
thank's

**Comment by ramonfontes** [comment]
Dear,

Mininet-WiFi only captures the position of the vehicles from sumo's API. If you cannot see them in sumo-gui, this means that this problem isn't related to mn-wifi.

**Comment by lamiael16** [comment]
Thank you.

**Comment by lamiael16** [comment]
Hi Ramon,
Please, can you try vanet-sumo.py with 50 cars if it works for you ( I read
in old issue that there is a problem with vanet.py if more than 20 cars are
used in the script, perhaps it is the same thing with vanet-sumo.py, I
don't know, I just try to find explaining my problem)?
I it work for you that mean there are a problem with my ubuntu or my VM.
I send my issue to sumo mail list but I didn't get a clear response.
Sorry, but please juste to check this possibility, Before I change my Vm.
Thank you so much for your help and answers.

**Comment by ramonfontes** [comment]
Could you share your sumo file which has 50 cars? I need all the sumo files: net, poly and route files.

**Comment by lamiael16** [comment]
Hi ramon,
Thank you so much for your help, I share with you my file with 40 vehicles.
I will check vanet-sumo.py with the newest version of Sumo (1.3.1) as sumo
mailist suggest and see if it will resolve the issue. but by time, please
can you try my files on your system? did the capacity of my virtual machine
have an effect on script running?
Have a nice day.
Lamia

**Comment by ramonfontes** [comment]
Where are the files???

**Comment by lamiael16** [comment]
Hi ramon,
I put the files in attachment .

**Comment by ramonfontes** [comment]
Could you please tell me how did you attach files in this platform? I'm so sorry, but I can't be answering so many messages from you. Be more clear and objective! If you have files, please use plataforms like gist and share their links here.

**Comment by lamiael16** [comment]
Hi Ramon,
Sorry to be late, I had some personnel problem. I was in bad situation.
I used my gmail to send my response for this reason the files are not attached.
I have just opened my git and I put the file attached here in zip file.
Thank you so much and sorry for my late but It was due to force majeure.

[sumo_files.zip](https://github.com/intrig-unicamp/mininet-wifi/files/3666164/sumo_files.zip)

**Comment by ramonfontes** [comment]
There is a problem with the vehicle number 38 and the code worked after removing it. It seems that the edges aren't correctly defined for that vehicle. What is wrong with the edges? I don't know. You need to check it out.

**Comment by lamiael16** [comment]
Please, can you show me how can I identify the vehicle that causes a problem. I will use your method to remove all vehicles and generate a good scenarios.
Thank you so much.

**Comment by ramonfontes** [comment]
Look at the time the error occurs and then remove the vehicle where the depart time coincides with the error time.

**Comment by lamiael16** [comment]
I will do it , thank you so much, you are very helpful and kind.

**Comment by lamiael16** [comment]
Hi Ramon,
Please can you guide me how to debug your script vanet-sumo.py because when
I try to use print instruction inside the script to check the value of the
edge that struck the code, no thing is shown on screen.
ài know the environment of mining-wifi is not the same as simple execution
of python script, but I am sur there is a manner to visualize the value of
some variables just to see if it contains what I expect.
Thank you once again,
Lamia

**Comment by lamiael16** [comment]
HI ramón,
I found the method to print the value of variables.
thank you for all your help.
