### ISSUE TITLE
Does mininet-wifi support 802.11ax and RU concept?

### ISSUE THREAD

**Issue by tori22** [intrig-unicamp/mininet-wifi#275]
### Question1:
So far, it seems it support 802.11p and etc. Is 802.11ax excluded? (maybe RU management is needed in the future.)

### Question2:(optional)
I want to create a dense-wlan topology with neighboor aps influencing each other shown in codes. Can you help me make sure that wmediumd module and setPropagationModel choice are right?
  
    net = Mininet_wifi(controller=Controller, accessPoint=OVSKernelAP,       link=wmediumd,wmediumd_mode=interference,noise_threshold=-91,fading_coefficient=3)

    print "*** Creating nodes"
    h1 = net.addHost('h1', mac='00:00:00:00:00:01', ip='10.0.0.1/8')
    sta1 = net.addStation('sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8', position='70,50,0')
    sta2 = net.addStation('sta2', mac='00:00:00:00:00:03', ip='10.0.0.3/8', position='80,60,0')
    sta3 = net.addStation('sta3', mac='00:00:00:00:00:04', ip='10.0.0.4/8', position='90,70,0')
   
    ap1 = net.addAccessPoint('ap1', ssid='ssid-ap1', mode='g', channel='1',
                             position='50,50,0')
    ap2 = net.addAccessPoint('ap2', ssid='ssid-ap2', mode='g', channel='1',
                             position='70,60,0', range=30)
    ap3 = net.addAccessPoint('ap3', ssid='ssid-ap3', mode='g', channel='1',
                             position='90,90,0')
    ap4 = net.addAccessPoint('ap4', ssid='ssid-ap4', mode='g', channel='1',
                             position='110,70,0')
    
    c1 = net.addController('c1', controller=Controller)

    net.setPropagationModel(model="logDistance", exp = 5)
    print "*** Configuring wifi nodes"
    net.configureWifiNodes()

    print "*** Associating and Creating links"
    net.addLink(h1, ap1)
    net.addLink(ap1, ap2)
    net.addLink(ap2, ap3)
    net.addLink(ap3, ap4)

    """uncomment to plot graph"""
    net.plotGraph(max_x=250, max_y=150)

    net.setMobilityModel(time=0, model='RandomWayPoint', max_x=250, max_y=150,
                         min_v=3, max_v=5, seed=5, ac_method='ssf')

    print "*** Starting network"
    net.build()
    c1.start()
    ap1.start([c1])
    ap2.start([c1])
    ap3.start([c1])
    ap4.start([c1])
    

### Question3:(Very Important)
* 3.1 When I want to change an ap's txPower, should ap's range change at the same time in some way by myself? You know, ap has txpower and range these two attributes. I'm not sure whether they are implicitly related or not. Just changing txPower is enough?

* 3.2 I notice that channel number in examples is from 1 to 14. Does it mean only 2.4G frequency supported? What about 5.8G? Then number will be in accordance with common knowledge such as 165, 160?

* 3.3 When I want to change an ap's channel, should ap's frequency change at the same time in some way by myself? You know, ap has channel and frequency these two attributes. I'm not sure whether they are implicitly related or not. Just changing channel number is enough?

* 3.4 What about I want to change an ap's bandwidth not only channel? 

Thanks.
Look forward to your reply.

**Comment by ramonfontes** [comment]
- **Q1:** Regarding 802.11p I've submitted a patch to Linux Kernel [1](https://patchwork.kernel.org/patch/11183993/) and [2](https://patchwork.kernel.org/patch/11183995/) and mac80211_hwsim will support 802.11p by default soon. Regarding 802.11ax, since hostapd supports 802.11ax, Mininet-WiFi supports 802.11ax too. However, if you want to do a more realist scenario the 802.11ax rates need to be implemented in wmediumd too. It would be great to have some contribution in this regard.
- **Q2:** You can find the answer for this question through the literature.
- **Q3.1:** Yes. Signal range also changes - this works with the dev branch though.
- **Q3.2:** Since Mininet-WIFi supports 5GHz, it supports 5GHz channels too. This [sample file](https://github.com/intrig-unicamp/mininet-wifi/blob/master/examples/wmediumd_interference.py#L20) is configured with 5GHz: 
- **Q3.3:** If you change the channel, frequency also changes. You can confirm this with wireless tools such as iw/iwconfig.
- **Q3.4:** It depends on the wireless mode you choose.
