### ISSUE TITLE
ubuntu 18.04 lts installation issue

### ISSUE THREAD

**Issue by yogiex** [intrig-unicamp/mininet-wifi#380]
![1619014505037](https://user-images.githubusercontent.com/31413884/115568685-bf43c700-a2e6-11eb-948e-59ef7521c722.jpg)
hello i got problem with installation util/install.sh -Wlnfv with fresh ubuntu
thankss

**Comment by ramonfontes** [comment]
Hi,

I tried installing `six` and got the expected hash rather than yours. This probably means that most likely it just got corrupted during download, less likely is someone tried to serve you a malicious package using through MITM or something like that.

You may try install `six` again forcing it to download a fresh copy with --no-cache-dir.

**Comment by yogiex** [comment]
so i need to reinstall ubuntu or reinstall with ```--no-cache-dir``` ?

**Comment by ramonfontes** [comment]
As I said, you may trying to install the `six` package manually.

**Comment by yogiex** [comment]
still persist got error sir, install ```six``` manually

**Comment by ramonfontes** [comment]
Did you install `six` and still have the same problem with `six`?? This doesn't make sense..

**Comment by yogiex** [comment]
yes i tried install ```six``` manually and stil get problem with ```six```, or any other issue with dependency like pip or must use python3? or can i edit ```install.sh``` to remove line to install ```six```?

**Comment by ramonfontes** [comment]
You can use either python2 or python3.

**Comment by yogiex** [comment]
i switch to python3 to solved this problem, thanks sir
