### ISSUE TITLE
p2p commands do not work

### ISSUE THREAD

**Issue by struggle47** [intrig-unicamp/mininet-wifi#49]
Hi, after I run the code I want the nodes (sta1 and sta2) to discover each other. In Ubunutu, I would do that using p2p_find command. However, this doesn't work in here. No matter what p2p command I use (p2p_find, p2p_group_add etc.) I always get "FAIL" response from the CLI (by the way, before using p2p commands I call "sta1 wpa_cli" command). Please help!

**Comment by ramonfontes** [comment]
Hi,

Please use only one issue for the same subject. I will appreciate if you
close this one.

Sent from my android

On 21 Feb 2017 18:23, "struggle47" <notifications@github.com> wrote:

Hi, after I run the code I want the nodes (sta1 and sta2) to discover each
other. In Ubunutu, I would do that using p2p_find command. However, this
doesn't work in here. No matter what p2p command I use (p2p_find,
p2p_group_add etc.) I always get "FAIL" response from the CLI (by the way,
before using p2p commands I call "sta1 wpa_cli" command). Please help!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/49>, or mute the
thread
