### ISSUE TITLE
Station does not ping APs during handover.

### ISSUE THREAD

**Issue by 14vv1A0516** [intrig-unicamp/mininet-wifi#496]
Sir,

Case 1: I am trying to run station handover among access points. APs are in root namespace as I want to access internet. 

**AP1 - 10.0.0.100/8
AP2- 10.0.0.200/8 
sta - 10.0.0.10/8**

I don't understand why station pings both APs in AP1 region but does not ping AP2 when it enters AP2 region. One more thing observed is when station is in AP2 region, ping from AP2 to station happens but not from station to AP2(vice-versa). Can you please confirm if this is expected ?

Case 2: As mentioned in [490](https://github.com/intrig-unicamp/mininet-wifi/issues/490) issue, it is possible when APs are implemented in station mode. In this case, how to access internet ? Since, APs are not in root namespace, the network is isolated. 

Please help me. I tried many ways but failed.

**Comment by ramonfontes** [comment]
This is not an issue at all.

When you open an issue it is very very important a detailed description about the issue. Otherwise, we cannot help you. 

It seems to me that the questions you have is related to a setup problem or event a lack of understanding on how OVS works.

> I tried many ways but failed.

Which ways?

I suggest you to use the mailing for such questions.
