### ISSUE TITLE
The issue of  Same AP ssid

### ISSUE THREAD

**Issue by zhangzee** [intrig-unicamp/mininet-wifi#57]
hi , when I set the ap's ssid same ,like this:
ap1 = net.addAccessPoint( 'ap1', **ssid= 'ap-ssid'**, dpid='0000000100000001',mode= 'g', channel= '1', position='10,10,0', range='10' )
ap2 = net.addAccessPoint( 'ap2', **ssid= 'ap-ssid'**, dpid='0000000100000002', mode= 'g', channel= '1', position='25,10,0', range='10' )
ap3 = net.addAccessPoint( 'ap3', **ssid= 'ap-ssid'**, dpid='0000000100000003',mode= 'g', channel= '1', position='40,10,0', range='10' )
Except the attribute of dpid and position, others are same .

when a station moves among these three aps, it often failed to associate another ap , I don't know why 
 and Should I change some attribute values ?

**Comment by ramonfontes** [comment]
Hello,

How do you know about the association? Did you use iwconfig or iw? Isn't by
means of a traffic, right? You don't have to change any attribute value.

Sent from my android


On 22 Mar 2017 07:27, "zhangze" <notifications@github.com> wrote:

hi , when I set the ap's ssid same ,like this:
ap1 = net.addAccessPoint( 'ap1', *ssid= 'ap-ssid'*,
dpid='0000000100000001',mode= 'g', channel= '1', position='10,10,0',
range='10' )
ap2 = net.addAccessPoint( 'ap2', *ssid= 'ap-ssid'*,
dpid='0000000100000002', mode= 'g', channel= '1', position='25,10,0',
range='10' )
ap3 = net.addAccessPoint( 'ap3', *ssid= 'ap-ssid'*,
dpid='0000000100000003',mode= 'g', channel= '1', position='40,10,0',
range='10' )
Except the attribute of dpid and position, others are same .

when a station moves among these three aps, it often failed to associate
another ap , I don't know why
and Should I change some attribute values ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/57>, or mute the
thread

**Comment by zhangzee** [comment]
yes, I know it by using of iwconfig ,and when it move to ap3,the iwconfig result shows that  it also associated with ap2.
![image](https://cloud.githubusercontent.com/assets/22088840/24200194/4b051c90-0f47-11e7-9048-2cc90be63a07.png)

**Comment by ramonfontes** [comment]
Could u tell me the mac addr of ap1 and ap3?

**Comment by zhangzee** [comment]
ap1-wlan1 Link encap:Ethernet  HWaddr 02:00:00:00:01:00  
ap2-wlan1 Link encap:Ethernet  HWaddr 02:00:00:00:02:00
ap3-wlan1 Link encap:Ethernet  HWaddr 02:00:00:00:03:00

**Comment by ramonfontes** [comment]
What about your script?

**Comment by ramonfontes** [comment]
I couldn't observe any problem here. On the other hand I think there is no
need to set threads as daemon (https://github.com/intrig-
unicamp/mininet-wifi/commit/0c1356269543dc488d8eaf662cc1921b0479c062).
Perhaps it will solve the issue. Let's see.. Please clone the code and run
make install in order to recompile mininet-wifi.

2017-03-22 11:29 GMT-03:00 zhangze <notifications@github.com>:

**Comment by ramonfontes** [comment]
Actually daemon thread is still required. Please try it with the latest
commit and be sure that there is no other process of mininet-wifi running
simultaneously.

2017-03-22 14:51 GMT-03:00 Ramon Fontes <ramonreisfontes@gmail.com>:

**Comment by zhangzee** [comment]
did you change something else  except set threads as daemon , should I need to recompile mininet-wifi?  And I run the script after I reboot the system ,so I am sure there is no other process of mininet-wifi running.

**Comment by ramonfontes** [comment]
Yes. Only one change related to mutithread.

**Comment by zhangzee** [comment]
There is no problem when you run my script ? This is why .....
And if there is any difference between same ssid and different ssid ?

**Comment by ramonfontes** [comment]
There is no problem and there is no difference if the APs have the same
ssid or not.

Sent from my android

On 22 Mar 2017 23:43, "zhangze" <notifications@github.com> wrote:

There is no problem when you run my script ? This is why .....
And if there is any difference between same ssid and different ssid ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/57#issuecomment-288601171>,
or mute the thread

**Comment by zhangzee** [comment]
so I just change the ssid different to resolve this problem ......  But I don't think so and I  will try it again.

**Comment by ramonfontes** [comment]
If the problem still persists to you, it should work fine with the latest version of Mininet-WiFi if you use wmediumd.
