### ISSUE TITLE
Which controller can I use for mininet-wifi?

### ISSUE THREAD

**Issue by CoderFan** [intrig-unicamp/mininet-wifi#6]
Hi,I have installed the mininet-wifi. I think it is very great. I have a question which controller can be used to control the network of mininet-wifi? floodlight, Ryu, POX or that I have to modify them to support the feature of wifi?

**Comment by ramonfontes** [comment]
Hi, you can use any controller. In the current implementation there is a problem when send packets out to the incoming port. In this case, rules defined by an OpenFlow controller doesn't have effect.

**Comment by ramonfontes** [comment]
Hi, you can use any controller. In the current implementation there is a problem when send packets out to the incoming port. In this case, rules defined by an OpenFlow controller doesn't have effect.

**Comment by CoderFan** [comment]
Hi, thank you for the respond. I have use the floodlight controller with mininet-wifi, but the webUI of the floodlight can not correctly show that between the AP and the Station do not have the link. I think it is the problem that floodlight can not correctly recognize the AP and station, is'n it?

**Comment by ramonfontes** [comment]
Exactly! ;)

2016-04-12 22:14 GMT-03:00 lipeng <notifications@github.com>:

**Comment by CoderFan** [comment]
Thank you very much!
In the script "wifimesh.py", there is not a controller. Can we add a controller for it to control the stations? For the mininet-wifi, can it implement the wireless mess network with a controller?

**Comment by ramonfontes** [comment]
You can add a controller to control APs, not Stations. I mean, you can use
the controller to add flow entries directing the AP on how to forward
packets.

2016-04-13 20:54 GMT-03:00 lipeng <notifications@github.com>:

**Comment by CoderFan** [comment]
I want to use SDN in the wireless mesh network. You mean that I can use APs to implement the wireless mesh network and then use a controller to control the APs, don't you?

**Comment by ramonfontes** [comment]
Exactly!

2016-04-14 10:16 GMT-03:00 lipeng <notifications@github.com>:

**Comment by CoderFan** [comment]
Thank you! How does the controller link the AP? Directly by the wire?

**Comment by ramonfontes** [comment]
Yes. You should participate of our mailing list (
https://groups.google.com/forum/#!forum/mininet-wifi-discuss) in order
obtain more information on how it works. :)

2016-04-14 10:28 GMT-03:00 lipeng <notifications@github.com>:

**Comment by CoderFan** [comment]
Thank you for your help! I have sent the application to apply for participating of the mailing list just now. :)

**Comment by ramonfontes** [comment]
Good. Can I close this issue?

2016-04-14 10:45 GMT-03:00 lipeng <notifications@github.com>:

**Comment by CoderFan** [comment]
Yes. :)

**Comment by gauravbatra8** [comment]
Hello Ramon . I have a doubt, I want to simulate software defined mesh network using mininet-wifi. I see some examples where stations are moving and access points are fixed. In my project , I want to move my nodes which are simple openvswitch or access points. There will be no stations. Is it possible?

**Comment by hamzehmohammadnia** [comment]
Hi @ramonfontes ,

I had some thoughts through working with Mininet-wifi, with holding your description about:
a) If need to add a remote controller it needs to handle mobility or do it manually
b). current mininet-wifi is working with reference controller (default controller)

Now I have two questions:

1. is the reference controller defined in node.py at line number 2278: class Controller(Node)?

2. As you said earlier, the reference controller that is used for mininet in default is from mininet, right? then if I change the option parameter of --controller=remote controller and run 

https://github.com/itaimirin/SDN-Controller---Mininet-POX-/blob/master/IM_l2_learning.py 

it will work properly?


3. and last but not least, since you mentioned this is a wireless station (access point) that acts like a switch, and since when I traced controller on wireshark I have seen Port_in and Port_out flows, how controller setups rules on the access points (ovs switch) ? cuz there is no port to setup rules on it... 


Thank you in advance,
Best,
