### ISSUE TITLE
Dynamic AP channel modification

### ISSUE THREAD

**Issue by j05k0** [intrig-unicamp/mininet-wifi#61]
Hello, 
Can I change AP's channel during operation? If yes, then how to do so.

Thank you in advance.

**Comment by ramonfontes** [comment]
Hello,

I don't think so. To the best of my knowledge, hostapd doesn't allow
changing channel on-the-fly.

Sent from my android

On 3 Apr 2017 19:42, "Jozef Vaľko" <notifications@github.com> wrote:

Hello,
Can I change AP's channel during operation? If yes, then how to do so.

Thank you in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/61>, or mute the
thread

**Comment by j05k0** [comment]
Thank you for response.
What are my options? Do I have to stop AP, change channel and then start it up? Or channel assignment could be done only when creating AP? 

Thank you.

**Comment by ramonfontes** [comment]
Both possibilities should work.

If you chose the first one please note that when you start a topology, one
process for each AP is created. For example:

sudo mn --wifi
mininet-wifi> sh ps -aux | grep ap1-wlan1
root     22924  0.0  0.0  25620  2808 ?        Ss   20:25   0:00 *hostapd
-B mn22769_ap1-wlan1.apconf*
root     23024  0.0  0.0   4500   700 pts/5    S+   20:25   0:00 /bin/sh -c
ps -aux | grep ap1-wlan1
root     23026  0.0  0.0  14236  1012 pts/5    S+   20:25   0:00 grep
ap1-wlan1

Then, change *mn22769_ap1-wlan1.apconf *and run hostpad again.


2017-04-03 20:03 GMT-03:00 Jozef Vaľko <notifications@github.com>:

**Comment by ramonfontes** [comment]
You can try **chan_switch** by using hostapd_cli
