### ISSUE TITLE
Documentation for the different functions

### ISSUE THREAD

**Issue by adrianUPC** [intrig-unicamp/mininet-wifi#82]
I am new in mininet-WiFi and I have some questions:

    1.- Does it exist any "help" for the different functions, so I can see all the parameters that can be defined? For example, configuring the AP with 802.11ac? (I guess it is mode="ac" , but I am not sure). I have following all the tutorials/examples but maybe there is some kind of detailed documentation

    2.- How can I load an external controller using the python API?

**Comment by ramonfontes** [comment]
Hello,

1. Have you ever read the manual? Regarding 802.11ac it's correct.

2. The same way you do for Mininet.

Sent from my android

On 24 May 2017 05:59, "adrianUPC" <notifications@github.com> wrote:

I am new in mininet-WiFi and I have some questions:

1.- Does it exist any "help" for the different functions, so I can see
all the parameters that can be defined? For example, configuring the
AP with 802.11ac? (I guess it is mode="ac" , but I am not sure). I
have following all the tutorials/examples but maybe there is some kind
of detailed documentation

2.- How can I load an external controller using the python API?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/82>, or mute the
thread

**Comment by adrianUPC** [comment]
Thanks Ramon. 
Regarding the 802.11ac question, I was confused because in section 1.6.2 in the manual you employ variables "mode" and "ieee80211r". I thought that the "mode" is equivalent to the "hw_mode" in hostapd.conf. But in such a case, the 802.11ac should be configured as hw_mode=a and 80211ac=1.

Furthermore (please correct me if I am wrong) the channels at 5GHz are not defined in wifiChannel.py (i.e. 36, 40, 44, ...) I guess I should add this channels at that file.

Best Regards
Adrian

**Comment by ramonfontes** [comment]
Regarding 802.11r there is a problem: You can use any mode you want with 802.11r. That's why I had to use ieee80211='yes'. Do you have any suggestion for improving it? You don't have to set 80211ac=1. Only set mode='ac'. Have you checked this https://github.com/intrig-unicamp/mininet-wifi/blob/master/mininet/wifiChannel.py#L223?

**Comment by adrianUPC** [comment]
Thanks!
It seems I had an old version, I have update right now.

I am trying to set up an scenario where the configuration of the AP will be changed by an external controller. (opendaylight). I have seen your discussion https://github.com/intrig-unicamp/mininet-wifi/issues/58, and I will take into account that information. 

BR

**Comment by ramonfontes** [comment]
Thank you Adrian. You can clone the branch dev if you want. Please let me know if you have any doubt/suggestion.

Regards,
Ramon

**Comment by adrianUPC** [comment]
Hi Ramon, 
I have been reading the different links you have been providing in other discussions about how managing the PHY-layer of APs (i.e. using CAPWAP). If I am not wrong, it seems that something is needed at the virtual AP (I do not know if at hostapd level or what else) in order to "react" to the CAPWAP commands. I guess that using the openCAPWAP approach is not an easy modification at the mininet-WIFI. Are you considering to add such functionality in your system?

Furthermore, playing around with the CAPWAP it seems that an IP for the desired AP is needed to obtain the information. In mininet-WIFI you cannot define the IP for AP, just for stations, am I right?

Thanks

**Comment by ramonfontes** [comment]
Hi Adrian,

You don't have to modify Mininet-WiFi. I think you can do it by changing
hostapd. As you can see from this code
<https://github.com/iosifpeterfi/openCAPWAP-OpenWRT/tree/master/hostapd_wrapper>
or
even this other one
<https://github.com/carosio/meta-caros/tree/master/recipes-connectivity/hostapd/hostapd-capwap-ac-1.1>,
capwap can be supported by hostapd applying the patch available at those
codes. I know, that version of hostapd is old and totally different, but I
think it can be supported if you follow up the changes applied from the
patch. Why not? I couldn't work on this thread yet, but I have plans to do
so.

Regarding the IP address you can set it manually. It works automatically
only for UserAP and when inNamespace=True.

2017-06-19 12:42 GMT-03:00 adrianUPC <notifications@github.com>:

**Comment by ramonfontes** [comment]
Still a first release: https://github.com/ramonfontes/opencapwap-mininet-wifi

**Comment by iamxg** [comment]
Hi Ramon,
I run the example adhoc.py. I reset location of sta3 so that it is  not in communication range of sta1. But sta1 still can communication with sta3 (see graph). I don't know why. Could you tell me how to modify  it? Thank you!
Happy weekend!
![screenshot from 2017-08-19 23-03-32](https://user-images.githubusercontent.com/30093996/29492054-0af4ab20-8535-11e7-851c-70d23c4e3c08.png)

**Comment by iamxg** [comment]
Hi Ramon,
I run the example adhoc.py. I reset location of sta3 so that it is not in communication range of sta1. But sta1 still can communication with sta3 (see graph). I don't know why. Could you tell me how to modify it? Thank you!
Happy weekend!
![image](https://user-images.githubusercontent.com/30093996/29492059-3f06ec20-8535-11e7-8762-71948e408b68.png)

**Comment by ramonfontes** [comment]
Hi,

Is wmedium enabled?

**Comment by iamxg** [comment]
Hi Ramon,


				
Thank you forreplying timely. wmedium is enabled on my computer because

				
But there is no thisproblem when I run another an example position.py.


 
 




Best Regards,


Xian Guo

 

 

-----Original Message-----

**Comment by Lucho0718** [comment]
Hi Ramon

Look what happens is that I have been working on the creation of a Wi-Fi network under the 802.11ac standard, I was reviewing in previous comments that the implementation of this standard only requires the configuration mode = 'ac', try it that way and the The result was that the stations connected to the different APs in the network could not be communicated, as if they did not have a connection. Reason why I decided to observe the instructions of the hostapd.conf file and there I could notice that there was an information which allowed to implement the standard to work with VHT, the configuration was hw_mode = a, which is used to specify that in the 5 GHz band is used with VHT and then it is configured ieee80211ac = 1 to activate the standard. What I would like to know is whether through this form if the 802.11ac standard is configured correctly or that other alternatives could be implemented.

I would also like to ask if there is any way to do a kind of channel modeling for this rule, for example by modifying some parameters within a file, or if the only way to do it would be through commands such as supported_chan_width, Tx STBC , which are also indicated within the hostapd.conf file.

**Comment by ramonfontes** [comment]
Hi,

Did you check the ap conf file in your work directory? I think it includes
all "ac" information we need to make it work with hostapd.

Regarding the channel modelling for "ac", you may want to take a look at
the signal table of wmediumd -
https://github.com/ramonfontes/wmediumd/blob/mininet-wifi/tests/signal_table_ieee80211ax
.

Sent from my android

On 8 Mar 2018 15:46, "Lucho0718" <notifications@github.com> wrote:

Hi Ramon

Look what happens is that I have been working on the creation of a Wi-Fi
network under the 802.11ac standard, I was reviewing in previous comments
that the implementation of this standard only requires the configuration
mode = 'ac', try it that way and the The result was that the stations
connected to the different APs in the network could not be communicated, as
if they did not have a connection. Reason why I decided to observe the
instructions of the hostapd.conf file and there I could notice that there
was an information which allowed to implement the standard to work with
VHT, the configuration was hw_mode = a, which is used to specify that in
the 5 GHz band is used with VHT and then it is configured ieee80211ac = 1
to activate the standard. What I would like to know is whether through this
form if the 802.11ac standard is configured correctly or that other
alternatives could be implemented.

I would also like to ask if there is any way to do a kind of channel
modeling for this rule, for example by modifying some parameters within a
file, or if the only way to do it would be through commands such as
supported_chan_width, Tx STBC , which are also indicated within the
hostapd.conf file.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/82#issuecomment-371584049>,
or mute the thread

**Comment by Lucho0718** [comment]
Hi Ramon

First, thanks for the previous answer, I'm going to consult the aforementioned file to improve the implementation of ac mode and look at the modeling of the channel.

Second, I would like to ask if with the mininet-wifi tool, it is possible to implement subnetworks through subnetting. That is, once subnetting is done and having the addresses of the subnets, it is possible to implement something like 2 or 3 to group the hosts and stations in different networks.

Thank you for your attention.
