### ISSUE TITLE
Does the code for Mininet-WiFi maintain updates from Mininet?

### ISSUE THREAD

**Issue by agawande** [intrig-unicamp/mininet-wifi#88]
Hi

Mininet-WiFi is a fork of Mininet, so does it maintain any updates from Mininet?
Can the new functionality (i.e. of Mininet-Wifi) be separated from Mininet easily for easier understanding such that Mininet is a dependency? Or is there a specific reason Mininet-Wifi needs to be a fork of Mininet?

Thanks.

**Comment by ramonfontes** [comment]
We keep Mininet-WiFi updated when there is change in Mininet, of course. You cannot separate them easily, because Mininet-WiFi inherits all functions from Mininet, specially links, nodes, etc. Further information about Mininet-WiFi is available at the manual.

Is there any specific doubt about how Mininet-WiFi work?

**Comment by agawande** [comment]
Okay, thanks for the quick answer! I still need to read the manual more thoroughly and carefully to understand Mininet-Wifi. Is Github issues the correct place for questions or should I post in the Google groups?

**Comment by ramonfontes** [comment]
Whatever you want.. But you can use this place for issues/errors and the group for questions, doubts, etc.
