### ISSUE TITLE
Mobility is only visual?

### ISSUE THREAD

**Issue by eSoares** [intrig-unicamp/mininet-wifi#95]
Hi,

In the example "mobility.py" shouldn't Station 1 lose the connection with the AP when he moves out of range?
If I try to ping AP from station 1 it was communication without any problem.

Thank you in advance for your help.

**Comment by ramonfontes** [comment]
It should lose the connection if you use UserAP switch (instead of OVS)
with inNamespace=True. OVS doesn't support inNamespace.

Ps. There is a topic in the mailing list approaching this issue.

Sent from my android

On 30 Jun 2017 12:44, "eSoares" <notifications@github.com> wrote:

Hi,

In the example "mobility.py" shouldn't Station 1 lose the connection with
the AP when he moves out of range?
If I try to ping AP from station 1 it was communication without any problem.

Thank you in advance for your help.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/intrig-unicamp/mininet-wifi/issues/95>, or mute the
thread
