### ISSUE TITLE
Exception: Please shut down the controller which is running on port 6653:

### ISSUE THREAD

**Issue by slremy** [intrig-unicamp/mininet-wifi#96]
This error message perplexed me for a while on a fresh install.. when running `sudo mn`
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/871503/27930643-09cd9322-62a0-11e7-8481-0919423e13f2.png">

It turns out the problem was "resolved" by `sudo cp /usr/bin/ovs-testcontroller /usr/bin/ovs-controller`
Was this the appropriate strategy for addressing the issue?
Could the error message be updated to be more informative (at least to new newbies like me?)

**Comment by ramonfontes** [comment]
There are many possibilities for addressing such issue. As the message
says, there is another controller running on port 6653. So, what do you
have to do? Kill its process!

With *ps -aux | grep controller *you will see the process ID.

2017-07-06 17:12 GMT-03:00 slremy <notifications@github.com>:

**Comment by slremy** [comment]
Hi Ramon
The controller that was running on 6653 was actually started by mininet, so the issue wasn't really about killing the process since it didn't quite solve the problem. The problem appeared to be that the controller needed to be named ovs-controller (there wasn't an ovs-controller when open vswitch was installed at least on Ubuntu 16.04).

**Comment by ramonfontes** [comment]
hmm.. I don't think so. I can always solve such issue when its process is killed. I don't know how did you install Mininet-WiFi without ovs-controller (since it is installed by default). Anyway, what I want to says is that: The issue is solved killing is process and I've never needed to use your solution.

**Comment by slremy** [comment]
I installed mininetwifi from source. The controller that was installed (for me at least) when the install script was complete was the ovs-testcontroller (there was no ovs-controller at that time). From the time stamps on the executables in /bin it seems that ovs-testcontroller was installed before the install script was executed. 

I'll consider this issue closed, but hopefully this information might help someone else if they happen to have this issue.

**Comment by deeptadevkota** [comment]
Try running the command: sudo fuser -k 6653/tcp
Hope this helps!

**Comment by shadiSummer** [comment]
I had the same problem. Since I ran the Onos controller earlier, While I was trying to run the Mininet controller, I got the error below: 

Exception: Please shut down the controller which is running on port 6653:
Active Internet connections (servers and established)
tcp        0      0 0.0.0.0:6653            0.0.0.0:*               LISTEN      8818/ovs-testcontro

To solve the problem, Simply terminating Onos wouldn't help, So I ran the command below and it helped.

sudo fuser -k 6653/tcp


It worked. :)

**Comment by htanwar922** [comment]
```bash
service openvswitch-testcontroller stop
```
